language: objective-c
osx_image: xcode7.3
before_install:
- gem install cocoapods # Since Travis is not always on latest version
xcode_workspace: iosMath.xcworkspace # path to your xcodeproj folder
xcode_scheme:
- iosMath
- MacOSMath
xcode_sdk:
- iphonesimulator9.3
- macosx10.11
matrix:
    exclude:
        - xcode_scheme: iosMath
          xcode_sdk: macosx10.11
        - xcode_scheme: MacOSMath
          xcode_sdk: iphonesimulator9.3
